services = [
  {
    '_id': '1',
    'name': 'NAPPA ITALIA LEATHER',
    'image': '/images/blackleather.png',
    'description':
      'Nappa Italia is an OEM style, European leather embossed with the quintessential nappa haircell print. ',
    'category': 'Leather',
    'price': 89.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'GROZ-BECKERT NEEDLES',
    'image': '/images/needles.png',
    'description':
      'Most common for all kinds of lockstitch applications. For use on woven fabrics, leather and artificial leather and coated fabrics',
    'category': 'Needles',
    'price': 599.99,
    'countInStock': 0,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'ALCANTARA FOAM BACKED',
    'image': '/images/foam.png',
    'description':
      'Alcantara Pannel with foam...save time in not needing to apply your own foam! Great for multiple uses especially headliners. Relicate only supplies genuine Alcantara that is Made in Italy',
    'brand': 'Alcantara',
    'category': 'Thread',
    'price': 929.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'SERABOND BONDED',
    'image': '/images/thread.png',
    'description':
      'Serabond is a bonded polyester thread with outstanding UV resistance suitable for outdoor applications such as marine, motorcycle seats and convertible cars',
    'brand': 'SERABOND',
    'category': 'Electronics',
    'price': 399.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'MK7 CLARK PLAID FABRIC',
    'image': '/images/Plaid.png',
    'description':
      'The iconic tartan look! Clark plaid seat fabric is OEM VW® Golf MK7 GTI cloth. When shopping for Clark plaid, note that ours is Made in Germany, is foam backed, and is 59" wide.',
    'brand': 'CLARK',
    'category': 'Electronics',
    'price': 49.99,
    'countInStock': 0,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'WESTFALIA PLAID FABRIC',
    'image': '/images/GreenPlaid.png',
    'description':
      'Westfalia plaid fabric was original in mid to late 70',
    'brand': 'WESTFALIA',
    'category': 'Electronics',
    'price': 29.99,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
]
